Algoritmo sin_titulo
	DEFINIR NUM1,NUM2,RES Como Entero
	ESCRIBIR "INGRESAR NUMERO"
	LEER NUM1 
	ESCRIBIR "INGRESAR NUMERO"
	LEER NUM2
	ESCRIBIR NUM1, " * " NUM2, " = "
	LEER RES 
	ESCRIBIR "EL RESULTADO ES", NUM1 * NUM2,"TU RESPUESTA ES", RES = NUM1 * NUM2
FinAlgoritmo
